DATAUP-748 use locale en_US & other cleanup
kbase/relation_engine pull request #114
Opened 2022-04-29 18:49 UTC by n1mus

- [ ] I updated the README.md docs to reflect this change.

For changes to the codebase:

- [ ] I have written tests to cover this change.
- [x] This is not a breaking API change OR
- [ ] This is a breaking API change and I have incremented the API version and added a summary to CHANGELOG.md.

2022-04-29 18:53 UTC, n1mus commented on client_src/test/test_integration.py
> -from relation_engine_client import REClient
This was confusing since `relation_engine_client` is a directory with an `__init__.py` that defined `__all__` with `main.REClient`

2022-04-29 18:53 UTC, n1mus commented on client_src/test/test_integration.py
> +    )
Just ignore this "intermittent" failure

2022-04-29 18:54 UTC, n1mus commented on relation_engine_server/utils/json_validation.py
> +        elif scheme in ["http", "https"]:
Autoformatters

2022-04-29 18:54 UTC, n1mus commented on spec/stored_queries/generic/fulltext_search.yaml
> -# Should be REVISED or DEPRECATED.
I wrote this and I know it's not being used because of performance issues so axed the cruft

2022-04-29 18:55 UTC, n1mus commented on spec/test/stored_queries/test_fulltext_search.py
> -class TestFulltextSearchStoredQuery(unittest.TestCase):
Removed tests pertaining to `spec/stored_queries/generic/fulltext_search.yaml`

2022-04-29 21:03 UTC, ialarmedalien requested changes
Can you do a little more investigation into the admin query failure? Better still, remove that change from this PR (the rest is fine) and then do some investigation in another PR.

2022-04-29 22:16 UTC, n1mus commented on .dockerignore
> +tmp/
These are generated by the comprehensive query testing, or any output files can go here

2022-04-29 22:17 UTC, n1mus commented on Makefile
> -	docker-compose build
Forgot "down", and the "build" is redundant since the other make targets do it

2022-04-29 22:22 UTC, n1mus commented
Yep, was planning on that

2022-04-30 01:12 UTC, ialarmedalien approved these changes
LGTM

2022-04-30 01:12 UTC, merged