add ontology_get_associated_samples
kbase/relation_engine pull request #65
Opened 2021-01-13 22:06 UTC by zhlu9890

- [ ] I updated the README.md docs to reflect this change.

For changes to the codebase:

- [ ] I have written tests to cover this change.
- [x] This is not a breaking API change OR
- [ ] This is a breaking API change and I have incremented the API version and added a summary to CHANGELOG.md.

2021-01-14 19:22 UTC, ialarmedalien commented on spec/stored_queries/ontology/ontology_get_associated_samples.yaml
> +# Get all samples reference this term
Missing some words/letters in this line?

You can add a `description` parameter below `name` with this information in it.

2021-01-14 19:23 UTC, ialarmedalien commented on spec/stored_queries/ontology/ontology_get_associated_samples.yaml
> +      description: Ontology id of the term you want to get all the ancestors of
capitalise ID

2021-01-14 19:25 UTC, ialarmedalien commented on spec/stored_queries/ontology/ontology_get_associated_samples.yaml
> +query: |
Can you add some automated tests for this query?

2021-01-14 19:28 UTC, ialarmedalien commented on spec/stored_queries/ontology/ontology_get_associated_samples.yaml
> +      title: Ontology terms collection name
Can you explain this more and/or give some examples?

See example of a stored query with full descriptions:

https://github.com/kbase/relation_engine/blob/develop/spec/stored_queries/djornl/djornl_fetch_clusters.yaml

2021-01-15 17:09 UTC, jayrbolton commented
The query looks okay to me. @zhlu9890 Do you think you would have time to add tests for this?

2021-01-16 05:02 UTC, zhlu9890 commented
@jayrbolton, I don't have time to add test for now.

2021-01-20 04:21 UTC, ialarmedalien requested changes
Please fix the capitalisation and clarify the description of `@onto_terms`.

2021-01-20 16:07 UTC, zhlu9890 commented
I have fixed the capitalisation and add the description and examples of @onto_terms.

2021-01-20 16:15 UTC, ialarmedalien approved these changes
👍

2021-01-20 16:47 UTC, merged